project_id: 453204
base_path: ./l10n
base_url: https://api.crowdin.com
preserve_hierarchy: true

files:
  - source: "/**/*_en_GB.json"
    translation: "%original_path%/%file_name%%locale_with_underscore%.json"
    translation_replace:
      en_GB: ""
